export const SEARCH_CITY = 'SEARCH_CITY';
export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const UPDATE_CITY ='UPDATE_CITY';